package com.aathif.web.domain.compliance;

public enum ComplaintType {
    HARASSMENT,
    DISCRIMINATION,
    WORKPLACE_SAFETY,
    SALARY_AND_BENEFITS,
    UNFAIR_TREATMENT,
    DISCIPLINARY_ACTIONS,
    PRIVACY_AND_SECURITY,
    INTERPERSONAL_CONFLICTS,
    WHISTLEBLOWER_COMPLAINTS,
    ACCOMMODATION_REQUESTS,
    TECHNOLOGY_AND_EQUIPMENT,
    OTHER
}
